### ISSUE TITLE
Systematically Check all Awards for Gaps

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/SIGPLAN.github.io#13]

**Comment by jhstanton** [comment]
Award | Years Awarded (on sigplan site) | Years missing
-------- | ------------------------------------------ | ------------------
programming lang achievement     | 2014 - 1997 |
distinguished service            | 2014 - 2012 |
programming lang software award | none listed |
robin milner    | 2014 - 2012 |
dissertation         | 2014 - 2011 | 2011, 2004 
ICFP             | 2014 - 2006 |
OOPSLA           | 2014 - 2007 |
PLDI             | 2014 - 2000 |
POPL             | 2014 - 2003 |
Vlissides        | 2014 - 2008 |
ACM Fellows List | 2013 - 1994 |

**Comment by MatthewFluet** [comment]
Closing old issues for new EC and InfoDir (see #118).
