### ISSUE TITLE
Adding election news

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/SIGPLAN.github.io#32]
Dear SIG Member,

In accordance with ACM Bylaw 6, the following SIGs will hold elections in 2015: SIGACCESS, SIGACT, SIGAPP, SIGARCH, SIGBED, SIGBio, SIGCHI, SIGDA, SIGecom, SIGEVO, ACM SIGGRAPH, SIGITE, SIGMETRICS, SIGMIS, SIGOPS, SIGPLAN, SIGSOFT, and SIGWEB.

ACM Policy and Procedures require that those SIGs holding elections notify their membership of candidates for elected offices. To see the slate of candidates, please visit the 2015 ACM SIG Election site, http://www.acm.org/sigs/elections .

In accordance with the SIG Bylaws, additional candidates may be placed on the ballot by petition. All candidates must be Professional Members of ACM, as well as members of the SIG. Anyone interested in petitioning must inform ACM Headquarters (Pat Ryan, ACM, 2 Penn Plaza, Suite 701, NY, NY 10121; ryan_p@acm.org) and the SIG Viability Advisor (Will Tracz, will.tracz@acm.org) of their intent to petition by 16 March 2015.

Additional information will appear in the February issue of ACM MemberNet and on the 2015 ACM SIG Election site.

Monique Chang
ACM SIG Elections Coordinator
Office of Policy and Administration

**Comment by MatthewFluet** [comment]
Closing old issues for new EC and InfoDir (see #118).
