### ISSUE TITLE
Reconsider the major links

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/SIGPLAN.github.io#33]
Two minor points.
1. The pages
   
   Information for Authors Submitting Papers
   
   General Chair Guidelines
   
   Program Chair Guidelines
   
   (and Referee Guideline, if we add it)

include lists of useful links. Can these be cross-listed on the

  Resources

page? Copy and paste means they will get out of sync, so use a pointer to the relevant section of the relevant page instead, or 'transclusion' if the content management system will handle it.
1. Every page has a list of major links at the top:

Home
Awards
Conferences
Resources
Research Highlights
Membership
Publications
I found this confusing, because the information I refer to most commonly is

  Conference Information

and this is only accessible from the home page. Can we please either:
- ensure that all information can be reached from one of the quick links
  
  (that is, that they provide a partition of all the information of the web pages), or
- add 'Conference Information' to the quick links on every page, or
- remove the quick links, and just give a link to home.

The first option will help our readers most, but may be difficult; I'm perfectly happy with either of the second two options.

**Comment by MatthewFluet** [comment]
Closing old issues for new EC and InfoDir (see #118).
