### ISSUE TITLE
Add link for SIGPLAN Ada-Europe

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/SIGPLAN.github.io#35]
PS: It would be nice if you could include a link to the Ada-Europe
web-site [3] on the "SIGPLAN Resources" page [4], for example after
the "Ada Programming Language SIG" item in the "Other WWW sites on
Programming Languages" subsection.

[3] http://www.ada-europe.org
[4] http://www.sigplan.org/Resources/

**Comment by jhstanton** [comment]
Done

**Comment by MatthewFluet** [comment]
Closed by 8db1449.
