### ISSUE TITLE
Need to refactor instructions for awards

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/SIGPLAN.github.io#43]
Instructions for awards are currently split across web pages and an old PDF.  And parts of the PDF are out of date.  The information needs to be refactored, and ideally it would be done such that there could be a single point of truth for common information (such as the fact that nominations are stronger if you actually contact the potential supporters).

**Comment by MatthewFluet** [comment]
Closing old issues for new EC and InfoDir (see #118).
