### ISSUE TITLE
Update instructions for nominators

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/SIGPLAN.github.io#44]
Nominators need to be told that their nominations are stronger if they mmake contact with supporters beforehand.  But gently, so as not to discourage nominatinos.  This is an old TODO of Norman's; Phil suggested some language that appears on Piazza or in minutes somewhere.

Waiting on #43

**Comment by MatthewFluet** [comment]
Closing old issues for new EC and InfoDir (see #118).
